export const currentYear = 2025;

export const bracketData24: Record<string, string[]> = {
  east: [
    "uconn", "iowa_state", "illinois", "auburn", "san_diego_state", "byu", "washington_state", "florida_atlantic",
    "northwestern", "drake", "duquesne", "uab", "yale", "morehead_state", "south_dakota_state", "stetson"
  ],
  west: [
    "north_carolina", "arizona", "baylor", "alabama", "saint_marys", "clemson", "dayton", "mississippi_state",
    "michigan_state", "nevada", "new_mexico", "grand_canyon", "charleston", "colgate", "long_beach_state", "howard"
  ],
  midwest: [
    "purdue", "tennessee", "creighton", "kansas", "gonzaga", "south_carolina", "texas", "utah_state",
    "tcu", "colorado_state", "oregon", "mcneese", "samford", "akron", "saint_peters", "grambling_state"
  ],
  south: [
    "houston", "marquette", "kentucky", "duke", "wisconsin", "texas_tech", "florida", "nebraska",
    "texas_a&m", "colorado", "nc_state", "james_madison", "vermont", "oakland", "western_kentucky", "longwood"
  ]
};

// const TODO = [
//   "louisville", "uc_san_diego", "lipscomb", "alabama_state", "saint_francis_u",
//   "vanderbilt", "liberty", "montana", "robert_morris", "american", "mount_saint_marys",
//   "georgia", "wofford", "siu_edwardsville",
//   "omaha",
// ]

// S 11 - san_diego_state, north_carolina
// S 16 - alabama_state, saint_francis_u
// E 16 - american, mount_saint_marys
// MW 11 - texas, xavier

export const bracketData25: Record<string, string[]> = {
  south: [
    "auburn", "michigan_state", "iowa_state", "texas_a&m", "michigan", "ole_miss", "marquette", "louisville",
    "creighton", "new_mexico", "san_diego_state_or_north_carolina", "uc_san_diego", "yale", "lipscomb", "bryant", "alabama_state_or_saint_francis_u",
  ],
  east: [
    "duke", "alabama", "wisconsin", "arizona", "oregon", "byu", "saint_marys", "mississippi_state",
    "baylor", "vanderbilt", "vcu", "liberty", "akron", "montana", "robert_morris", "american_or_mount_saint_marys",
  ],
  midwest: [
    "houston", "tennessee", "kentucky", "purdue", "clemson", "illinois", "ucla", "gonzaga",
    "georgia", "utah_state", "texas_or_xavier", "mcneese", "high_point", "troy", "wofford", "siu_edwardsville",
  ],
  west: [
    "florida", "saint_johns", "texas_tech", "maryland", "memphis", "missouri", "kansas", "uconn",
    "oklahoma", "arkansas", "drake", "colorado_state", "grand_canyon", "unc_wilmington", "omaha", "norfolk_state",
  ],
};

export const bracketData: Record<number, Record<string, string[]>> = {
  2024: bracketData24,
  2025: bracketData25,
};


export const regionOrder: Record<number, string[]> = {
  2024: ["east", "south", "midwest", "west"],
  2025: ["south", "east", "midwest", "west"],
};

export const firstFourMapping: Record<number, Record<string, string>> = {
  2024: {},
  2025: {
    "san_diego_state_or_north_carolina": "san_diego_state_or_north_carolina",
    "alabama_state_or_saint_francis_u": "alabama_state",
    "american_or_mount_saint_marys": "american_or_mount_saint_marys",
    "texas_or_xavier": "texas_or_xavier",
  }
}

export const nicknames: Record<string, string> = {
    "akron": "zips",
    "alabama": "crimson tide",
    "alabama_state": "hornets",
    "american": "eagles",
    "appalachian_state": "mountaineers",
    "arizona_state": "sun devils",
    "arizona": "wildcats",
    "arkansas": "razorbacks",
    "auburn": "tigers",
    "baylor": "bears",
    "boise_state": "broncos",
    "bryant": "bulldogs",
    "butler": "bulldogs",
    "byu": "cougars",
    "central_connecticut_state": "blue devils",
    "charleston": "cougars",
    "chattanooga": "mocs",
    "cincinnati": "bearcats",
    "clemson": "tigers",
    "cleveland_state": "vikings",
    "colgate": "raiders",
    "colorado": "buffaloes",
    "colorado_state": "rams",
    "cornell": "big red",
    "creighton": "bluejays",
    "csu_fullerton": "titans",
    "davidson": "wildcats",
    "dayton": "flyers",
    "delaware": "blue hens",
    "drake": "bulldogs",
    "duke": "blue devils",
    "duquesne": "dukes",
    "eastern_kentucky": "colonels",
    "east_washington": "eagles",
    "fdu": "knights",
    "florida": "gators",
    "florida_atlantic": "owls",
    "furman": "paladins",
    "georgia": "bulldogs",
    "georgia_state": "panthers",
    "gonzaga": "bulldogs",
    "grambling_state": "tigers",
    "grand_canyon": "antelopes",
    "green_bay": "phoenix",
    "high_point": "purple panthers",
    "houston": "cougars",
    "howard": "bison",
    "illinois": "fighting illini",
    "indiana": "hoosiers",
    "indiana_state": "sycamores",
    "iona": "gaels",
    "iowa_state": "cardinals",
    "iowa": "hawks",
    "jacksonville_state": "gamecocks",
    "james_madison": "dukes",
    "kansas_state": "wildcats",
    "kansas": "jayhawks",
    "kennesaw_state": "owls",
    "kent_state": "golden flashes",
    "kentucky": "wildcats",
    "liberty": "flames",
    "lipscomb": "bisons",
    "little_rock": "trojans",
    "long_beach_state": "the beach",
    "longwood": "lancers",
    "louisiana": "ragin cajuns",
    "louisiana_tech": "bulldogs",
    "louisville": "cardinals",
    "loyola_chicago": "ramblers",
    "lsu": "tigers",
    "marquette": "golden eagles",
    "maryland": "terrapins",
    "mcneese": "cowboys",
    "memphis": "tigers",
    "merrimack": "warriors",
    "miami": "hurricanes",
    "michigan_state": "spartans",
    "michigan": "wolverines",
    "mississippi_state": "bulldogs",
    "missouri": "mizzou",
    "montana": "grizzlies",
    "montana_state": "fighting bobcats",
    "mount_saint_marys": "mountaineers",
    "morehead_state": "eagles",
    "murray_state": "racers",
    "nc_central": "eagles",
    "nc_state": "wolfpack",
    "nebraska": "cornhuskers",
    "new_mexico": "lobos",
    "new_mexico_state": "aggies",
    "new_orleans": "privateers",
    "norfolk_state": "spartans",
    "north_carolina": "tar heels",
    "north_dakota": "fighting hawks",
    "north_texas": "mean green",
    "northern_iowa": "panthers",
    "northern_kentucky": "norse",
    "northwestern": "wildcats",
    "notre_dame": "fighting irish",
    "oakland": "golden grizzlies",
    "ohio_state": "buckeyes",
    "oklahoma": "sooners",
    "ole_miss": "rebels",
    "omaha": "mavericks",
    "oral_roberts": "golden eagles",
    "oregon": "ducks",
    "penn_state": "nittany lions",
    "pittsburgh": "panthers",
    "providence": "friars",
    "purdue": "boilmakers",
    "quinnipiac": "bobcats",
    "richmond": "spiders",
    "robert_morris": "colonials",
    "rutgers": "scarlet knights",
    "saint_francis_u": "red flash",
    "saint_johns": "red storm",
    "saint_marys": "gaels",
    "saint_peters": "peacocks",
    "sam_houston": "bearkats",
    "samford": "bulldogs",
    "san_diego_state": "aztecs",
    "san_francisco": "dons",
    "seton_hall": "pirates",
    "siu_edwardsville": "cougars",
    "south_carolina": "gamecocks",
    "south_dakota_state": "jackrabbits",
    "south_florida": "bulls",
    "southeast_missouri_state": "redhawks",
    "stetson": "hatters",
    "tcu": "horned frogs",
    "tennessee": "volunteers",
    "texas_a&m_cc": "islanders",
    "texas_a&m": "aggies",
    "texas_southern": "tigers",
    "texas_state": "bobcats",
    "texas_tech": "red raiders",
    "texas": "longhorns",
    "toledo": "rockets",
    "troy": "trojans",
    "uab": "blazers",
    "ucla": "bruins",
    "uconn": "huskies",
    "ucsb": "bison",
    "uc_irvine": "anteaters",
    "uc_san_diego": "tritons",
    "unc_asheville": "bulldogs",
    "unc_wilmington": "seahawks",
    "usc": "trojans",
    "utah": "utes",
    "utah_state": "aggies",
    "vanderbilt": "commodores",
    "vcu": "rams",
    "vermont": "catamounts",
    "villanova": "wildcats",
    "virginia_tech": "hokies",
    "virginia": "cavaliers",
    "wagner": "seahawks",
    "wake_forest": "demon deacons",
    "washington_state": "cougars",
    "west_virginia": "mountaineers",
    "western_kentucky": "hilltoppers",
    "wisconsin": "badgers",
    "wofford": "terriers",
    "wright_state": "raiders",
    "wyoming": "cowboys",
    "xavier": "musketeers",
    "yale": "bulldogs",
    "nevada": "wolf pack",
    "princeton": "tigers"
}
